USE empresa;
CREATE TABLE pessoas (nome VARCHAR(100), cpf CHAR(11), descricao MEDIUMTEXT);
-- O VARCHAR SERVE PARA LIMITAR O NUMERO DE LETRAS QUE O USUÁRIO PODE COLOCAR NA STRING
-- O CHAR TEM A MESMA UTILIDADE MAS SERVE PARA LIMITAR UM NUMERO MENOR DE LETRAS
-- O MEDIUMTEXT SERVE PARA DEIXAR UM ESPAÇO "ILIMITADO" PARA O USUÁRIO FICAR LIVRE PARA ESCREVER.
